/*
 * generated by Xtext
 */
package gr.upatras.ece.wcl.radl2;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RadlRuntimeModule extends gr.upatras.ece.wcl.radl2.AbstractRadlRuntimeModule {

}
