/*
 * generated by Xtext
 */
package org.panlab.software.fsdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FSDLUiModule extends org.panlab.software.fsdl.ui.AbstractFSDLUiModule {
	public FSDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
//	@Override
//	public void configureContentProposalLabelProvider(Binder binder) {
//	  binder.bind(ILabelProvider.class)
//	    .annotatedWith(ContentProposalLabelProvider.class).to(FSDLLabelProvider.class);
//	}
	

}
