/*
* generated by Xtext
*/
package org.panlab.officedl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OfficeDLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/panlab/officedl/parser/antlr/internal/InternalOfficeDL.tokens");
	}
}
