/*
* generated by Xtext
*/
package org.panlab.software.fsdl2;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FSDLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.panlab.software.fsdl2.ui.internal.FSDLActivator.getInstance().getInjector("org.panlab.software.fsdl2.FSDL");
	}
	
}
