/*
 * generated by Xtext
 */
package org.panlab.software.fsdl2.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FSDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.panlab.software.fsdl2.ui.internal.FSDLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.panlab.software.fsdl2.ui.internal.FSDLActivator.getInstance().getInjector("org.panlab.software.fsdl2.FSDL");
	}
	
}
