/*
* generated by Xtext
*/
package gr.upatras.ece.nam.brokerdsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class BrokerDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
