/*
 * generated by Xtext
 */
package gr.upatras.ece.nam.fsdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FSDLUiModule extends gr.upatras.ece.nam.fsdl.ui.AbstractFSDLUiModule {
	public FSDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
