/*
* generated by Xtext
*/
package gr.upatras.ece.wcl.radl2;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RadlUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return gr.upatras.ece.wcl.radl2.ui.internal.RadlActivator.getInstance().getInjector("gr.upatras.ece.wcl.radl2.Radl");
	}
	
}
