/*
* generated by Xtext
*/
package gr.upatras.ece.nam.fsdl.ui.contentassist;

import gr.upatras.ece.nam.fsdl.ui.contentassist.AbstractFSDLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FSDLProposalProvider extends AbstractFSDLProposalProvider {

}
