/*
* generated by Xtext
*/
package gr.upatras.ece.wcl.ui.contentassist;

import gr.upatras.ece.wcl.ui.contentassist.AbstractSDLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SDLProposalProvider extends AbstractSDLProposalProvider {

}
