/*
* generated by Xtext
*/
package org.panlab.software.fsdl2.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.panlab.software.fsdl2.services.FSDLGrammarAccess;

public class FSDLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FSDLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.panlab.software.fsdl2.parser.antlr.internal.InternalFSDLParser createParser(XtextTokenStream stream) {
		return new org.panlab.software.fsdl2.parser.antlr.internal.InternalFSDLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RequestedFederationScenario";
	}
	
	public FSDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FSDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
