/*
 * generated by Xtext
 */
package gr.upatras.ece.wcl.radl2.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RadlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return gr.upatras.ece.wcl.radl2.ui.internal.RadlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return gr.upatras.ece.wcl.radl2.ui.internal.RadlActivator.getInstance().getInjector("gr.upatras.ece.wcl.radl2.Radl");
	}
	
}
