/*
 * generated by Xtext
 */
package org.panlab.software.officedl2.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OfficeDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.panlab.software.officedl2.ui.internal.OfficeDLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.panlab.software.officedl2.ui.internal.OfficeDLActivator.getInstance().getInjector("org.panlab.software.officedl2.OfficeDL");
	}
	
}
