/*
* generated by Xtext
*/
package gr.upatras.ece.wcl.radl2.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import gr.upatras.ece.wcl.radl2.services.RadlGrammarAccess;

public class RadlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RadlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected gr.upatras.ece.wcl.radl2.parser.antlr.internal.InternalRadlParser createParser(XtextTokenStream stream) {
		return new gr.upatras.ece.wcl.radl2.parser.antlr.internal.InternalRadlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RADL";
	}
	
	public RadlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RadlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
