/*
 * generated by Xtext
 */
package gr.upatras.ece.wcl;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SDLRuntimeModule extends gr.upatras.ece.wcl.AbstractSDLRuntimeModule {

}
