
/*
 * generated by Xtext
 */
 
package org.panlab.software.fsdl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class FSDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.panlab.software.fsdl.ui.internal.FSDLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.panlab.software.fsdl.ui.internal.FSDLActivator.getInstance().getInjector("org.panlab.software.fsdl.FSDL");
	}
	
}
