/*
* generated by Xtext
*/
package gr.upatras.ece.wcl.radl2.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class RadlOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
