/*
 * generated by Xtext
 */
package gr.upatras.ece.nam.brokerdsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import gr.upatras.ece.nam.brokerdsl.ui.internal.BrokerDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BrokerDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BrokerDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BrokerDSLActivator.getInstance().getInjector(BrokerDSLActivator.GR_UPATRAS_ECE_NAM_BROKERDSL_BROKERDSL);
	}
	
}
