/*
 * generated by Xtext
 */
package gr.upatras.ece.wcl;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RadlRuntimeModule extends gr.upatras.ece.wcl.AbstractRadlRuntimeModule {

	
//	//pros to paron kanw register egw to scope provider, mexri na ginei to bug pou linei to na exeis ola ta arxeia sto javaproject src
//	@Override
//    public Class<? extends IScopeProvider >  bindIScopeProvider() {
//        return RadlScopeProvider.class;
//    }
//
}
