/*
 * generated by Xtext
 */
package gr.upatras.ece.nam.fsdl;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.naming.IQualifiedNameProvider;

import gr.upatras.ece.nam.fsdl.scoping.myFSDLQualifiedNameProvider;
import gr.upatras.ece.nam.fsdl.valueconverter.FSDLValueConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FSDLRuntimeModule extends gr.upatras.ece.nam.fsdl.AbstractFSDLRuntimeModule {

	@Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return  FSDLValueConverter.class;
    }
	
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return myFSDLQualifiedNameProvider.class;
	}
	
}
