/*
 * generated by Xtext
 */
package gr.upatras.ece.nam.brokerdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BrokerDSLUiModule extends gr.upatras.ece.nam.brokerdsl.ui.AbstractBrokerDSLUiModule {
	public BrokerDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
