/*
* generated by Xtext
*/
package gr.upatras.ece.wcl.radl2.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import gr.upatras.ece.wcl.radl2.services.RadlGrammarAccess;

public class RadlParser extends AbstractContentAssistParser {
	
	@Inject
	private RadlGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected gr.upatras.ece.wcl.radl2.ui.contentassist.antlr.internal.InternalRadlParser createParser() {
		gr.upatras.ece.wcl.radl2.ui.contentassist.antlr.internal.InternalRadlParser result = new gr.upatras.ece.wcl.radl2.ui.contentassist.antlr.internal.InternalRadlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getResourceAdapterAccess().getConfCompleteAlternatives_7_4_0(), "rule__ResourceAdapter__ConfCompleteAlternatives_7_4_0");
					put(grammarAccess.getConfigurationParamAccess().getNameAlternatives_2_0(), "rule__ConfigurationParam__NameAlternatives_2_0");
					put(grammarAccess.getBindingParamAccess().getNameAlternatives_2_0(), "rule__BindingParam__NameAlternatives_2_0");
					put(grammarAccess.getSupportedChildTypeAccess().getNameAlternatives_2_0(), "rule__SupportedChildType__NameAlternatives_2_0");
					put(grammarAccess.getAllowedTypeAccess().getNameAlternatives_2_0(), "rule__AllowedType__NameAlternatives_2_0");
					put(grammarAccess.getProtocolAccess().getAlternatives(), "rule__Protocol__Alternatives");
					put(grammarAccess.getParameterTypeAccess().getPNameAlternatives_1_0(), "rule__ParameterType__PNameAlternatives_1_0");
					put(grammarAccess.getCommandAccess().getAlternatives(), "rule__Command__Alternatives");
					put(grammarAccess.getRulJava_paramAccess().getAlternatives(), "rule__RulJava_param__Alternatives");
					put(grammarAccess.getScriptParamAccess().getAlternatives(), "rule__ScriptParam__Alternatives");
					put(grammarAccess.getRuleHTTPAccess().getHMethodAlternatives_13_0(), "rule__RuleHTTP__HMethodAlternatives_13_0");
					put(grammarAccess.getRADLAccess().getGroup(), "rule__RADL__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getResourceAdapterAccess().getGroup(), "rule__ResourceAdapter__Group__0");
					put(grammarAccess.getResourceAdapterAccess().getGroup_2(), "rule__ResourceAdapter__Group_2__0");
					put(grammarAccess.getResourceAdapterAccess().getGroup_3(), "rule__ResourceAdapter__Group_3__0");
					put(grammarAccess.getResourceAdapterAccess().getGroup_4(), "rule__ResourceAdapter__Group_4__0");
					put(grammarAccess.getResourceAdapterAccess().getGroup_5(), "rule__ResourceAdapter__Group_5__0");
					put(grammarAccess.getResourceAdapterAccess().getGroup_6(), "rule__ResourceAdapter__Group_6__0");
					put(grammarAccess.getResourceAdapterAccess().getGroup_7(), "rule__ResourceAdapter__Group_7__0");
					put(grammarAccess.getConfigurationParamAccess().getGroup(), "rule__ConfigurationParam__Group__0");
					put(grammarAccess.getConfigurationParamAccess().getGroup_3(), "rule__ConfigurationParam__Group_3__0");
					put(grammarAccess.getConfigurationParamAccess().getGroup_4(), "rule__ConfigurationParam__Group_4__0");
					put(grammarAccess.getBindingParamAccess().getGroup(), "rule__BindingParam__Group__0");
					put(grammarAccess.getBindingParamAccess().getGroup_3(), "rule__BindingParam__Group_3__0");
					put(grammarAccess.getBindingParamAccess().getGroup_4(), "rule__BindingParam__Group_4__0");
					put(grammarAccess.getSupportedChildTypeAccess().getGroup(), "rule__SupportedChildType__Group__0");
					put(grammarAccess.getSupportedChildTypeAccess().getGroup_3(), "rule__SupportedChildType__Group_3__0");
					put(grammarAccess.getAllowedTypeAccess().getGroup(), "rule__AllowedType__Group__0");
					put(grammarAccess.getAllowedTypeAccess().getGroup_3(), "rule__AllowedType__Group_3__0");
					put(grammarAccess.getParameterTypeAccess().getGroup(), "rule__ParameterType__Group__0");
					put(grammarAccess.getRuleSSHAccess().getGroup(), "rule__RuleSSH__Group__0");
					put(grammarAccess.getRuleJavaWrapperAccess().getGroup(), "rule__RuleJavaWrapper__Group__0");
					put(grammarAccess.getRuleJavaWrapperAccess().getGroup_4(), "rule__RuleJavaWrapper__Group_4__0");
					put(grammarAccess.getRuleJavaWrapperAccess().getGroup_4_1(), "rule__RuleJavaWrapper__Group_4_1__0");
					put(grammarAccess.getEntryCommandAccess().getGroup(), "rule__EntryCommand__Group__0");
					put(grammarAccess.getEntryCommandAccess().getGroup_3(), "rule__EntryCommand__Group_3__0");
					put(grammarAccess.getEntryCommandAccess().getGroup_3_1(), "rule__EntryCommand__Group_3_1__0");
					put(grammarAccess.getAssignCommandAccess().getGroup(), "rule__AssignCommand__Group__0");
					put(grammarAccess.getAssignCommandAccess().getGroup_6(), "rule__AssignCommand__Group_6__0");
					put(grammarAccess.getAssignCommandAccess().getGroup_6_1(), "rule__AssignCommand__Group_6_1__0");
					put(grammarAccess.getRulSSH_commandsAccess().getGroup(), "rule__RulSSH_commands__Group__0");
					put(grammarAccess.getRulSSH_commandsAccess().getGroup_2(), "rule__RulSSH_commands__Group_2__0");
					put(grammarAccess.getRuleHTTPAccess().getGroup(), "rule__RuleHTTP__Group__0");
					put(grammarAccess.getRuleHTTPAccess().getGroup_15(), "rule__RuleHTTP__Group_15__0");
					put(grammarAccess.getRuleHTTPAccess().getGroup_16(), "rule__RuleHTTP__Group_16__0");
					put(grammarAccess.getRuleHTTP_URLAccess().getGroup(), "rule__RuleHTTP_URL__Group__0");
					put(grammarAccess.getRuleHTTP_URLAccess().getGroup_2(), "rule__RuleHTTP_URL__Group_2__0");
					put(grammarAccess.getRuleXMLRPCAccess().getGroup(), "rule__RuleXMLRPC__Group__0");
					put(grammarAccess.getRuleXMLRPCAccess().getGroup_7(), "rule__RuleXMLRPC__Group_7__0");
					put(grammarAccess.getRuleXMLRPCAccess().getGroup_12(), "rule__RuleXMLRPC__Group_12__0");
					put(grammarAccess.getRADLAccess().getImportsAssignment_0(), "rule__RADL__ImportsAssignment_0");
					put(grammarAccess.getRADLAccess().getResourceAdapterAssignment_1(), "rule__RADL__ResourceAdapterAssignment_1");
					put(grammarAccess.getImportAccess().getImportURIAssignment_1(), "rule__Import__ImportURIAssignment_1");
					put(grammarAccess.getResourceAdapterAccess().getNameAssignment_1(), "rule__ResourceAdapter__NameAssignment_1");
					put(grammarAccess.getResourceAdapterAccess().getImplnameAssignment_2_1(), "rule__ResourceAdapter__ImplnameAssignment_2_1");
					put(grammarAccess.getResourceAdapterAccess().getByofficeAssignment_2_3(), "rule__ResourceAdapter__ByofficeAssignment_2_3");
					put(grammarAccess.getResourceAdapterAccess().getConfParamsAssignment_3_2(), "rule__ResourceAdapter__ConfParamsAssignment_3_2");
					put(grammarAccess.getResourceAdapterAccess().getBindParamsAssignment_4_2(), "rule__ResourceAdapter__BindParamsAssignment_4_2");
					put(grammarAccess.getResourceAdapterAccess().getChildParamsAssignment_5_2(), "rule__ResourceAdapter__ChildParamsAssignment_5_2");
					put(grammarAccess.getResourceAdapterAccess().getAllowParamsAssignment_6_2(), "rule__ResourceAdapter__AllowParamsAssignment_6_2");
					put(grammarAccess.getResourceAdapterAccess().getConfCompleteAssignment_7_4(), "rule__ResourceAdapter__ConfCompleteAssignment_7_4");
					put(grammarAccess.getResourceAdapterAccess().getProtocolAssignment_7_7(), "rule__ResourceAdapter__ProtocolAssignment_7_7");
					put(grammarAccess.getConfigurationParamAccess().getParamTypeAssignment_1(), "rule__ConfigurationParam__ParamTypeAssignment_1");
					put(grammarAccess.getConfigurationParamAccess().getNameAssignment_2(), "rule__ConfigurationParam__NameAssignment_2");
					put(grammarAccess.getConfigurationParamAccess().getDefValueAssignment_3_1(), "rule__ConfigurationParam__DefValueAssignment_3_1");
					put(grammarAccess.getConfigurationParamAccess().getDescriptionValueAssignment_4_2(), "rule__ConfigurationParam__DescriptionValueAssignment_4_2");
					put(grammarAccess.getBindingParamAccess().getParamTypeAssignment_1(), "rule__BindingParam__ParamTypeAssignment_1");
					put(grammarAccess.getBindingParamAccess().getNameAssignment_2(), "rule__BindingParam__NameAssignment_2");
					put(grammarAccess.getBindingParamAccess().getDefValueAssignment_3_1(), "rule__BindingParam__DefValueAssignment_3_1");
					put(grammarAccess.getBindingParamAccess().getDescriptionValueAssignment_4_2(), "rule__BindingParam__DescriptionValueAssignment_4_2");
					put(grammarAccess.getSupportedChildTypeAccess().getParamTypeAssignment_1(), "rule__SupportedChildType__ParamTypeAssignment_1");
					put(grammarAccess.getSupportedChildTypeAccess().getNameAssignment_2(), "rule__SupportedChildType__NameAssignment_2");
					put(grammarAccess.getSupportedChildTypeAccess().getDefValueAssignment_3_1(), "rule__SupportedChildType__DefValueAssignment_3_1");
					put(grammarAccess.getAllowedTypeAccess().getParamTypeAssignment_1(), "rule__AllowedType__ParamTypeAssignment_1");
					put(grammarAccess.getAllowedTypeAccess().getNameAssignment_2(), "rule__AllowedType__NameAssignment_2");
					put(grammarAccess.getAllowedTypeAccess().getDefValueAssignment_3_1(), "rule__AllowedType__DefValueAssignment_3_1");
					put(grammarAccess.getParameterTypeAccess().getPNameAssignment_1(), "rule__ParameterType__PNameAssignment_1");
					put(grammarAccess.getRuleSSHAccess().getRemoteMachineAssignment_5(), "rule__RuleSSH__RemoteMachineAssignment_5");
					put(grammarAccess.getRuleSSHAccess().getRPortAssignment_9(), "rule__RuleSSH__RPortAssignment_9");
					put(grammarAccess.getRuleSSHAccess().getUsernameAssignment_13(), "rule__RuleSSH__UsernameAssignment_13");
					put(grammarAccess.getRuleSSHAccess().getPasswordAssignment_17(), "rule__RuleSSH__PasswordAssignment_17");
					put(grammarAccess.getRuleSSHAccess().getCommandsAssignment_21(), "rule__RuleSSH__CommandsAssignment_21");
					put(grammarAccess.getRuleSSHAccess().getCommandsDeleteAssignment_25(), "rule__RuleSSH__CommandsDeleteAssignment_25");
					put(grammarAccess.getRuleJavaWrapperAccess().getClassnameAssignment_2(), "rule__RuleJavaWrapper__ClassnameAssignment_2");
					put(grammarAccess.getRuleJavaWrapperAccess().getConstructorParamsAssignment_4_0(), "rule__RuleJavaWrapper__ConstructorParamsAssignment_4_0");
					put(grammarAccess.getRuleJavaWrapperAccess().getConstructorParamsAssignment_4_1_1(), "rule__RuleJavaWrapper__ConstructorParamsAssignment_4_1_1");
					put(grammarAccess.getRuleJavaWrapperAccess().getCommandsAssignment_7(), "rule__RuleJavaWrapper__CommandsAssignment_7");
					put(grammarAccess.getEntryCommandAccess().getJavaFunctionNameAssignment_1(), "rule__EntryCommand__JavaFunctionNameAssignment_1");
					put(grammarAccess.getEntryCommandAccess().getCommandsAssignment_3_0(), "rule__EntryCommand__CommandsAssignment_3_0");
					put(grammarAccess.getEntryCommandAccess().getCommandsAssignment_3_1_1(), "rule__EntryCommand__CommandsAssignment_3_1_1");
					put(grammarAccess.getRulJava_paramStringAccess().getStringValueAssignment(), "rule__RulJava_paramString__StringValueAssignment");
					put(grammarAccess.getRulJava_paramIntAccess().getIntValueAssignment(), "rule__RulJava_paramInt__IntValueAssignment");
					put(grammarAccess.getRulJava_paraScriptAccess().getScriptparamValueAssignment(), "rule__RulJava_paraScript__ScriptparamValueAssignment");
					put(grammarAccess.getAssignCommandAccess().getScriptParamAssignment_2(), "rule__AssignCommand__ScriptParamAssignment_2");
					put(grammarAccess.getAssignCommandAccess().getJavaFunctionNameAssignment_4(), "rule__AssignCommand__JavaFunctionNameAssignment_4");
					put(grammarAccess.getAssignCommandAccess().getCommandsAssignment_6_0(), "rule__AssignCommand__CommandsAssignment_6_0");
					put(grammarAccess.getAssignCommandAccess().getCommandsAssignment_6_1_1(), "rule__AssignCommand__CommandsAssignment_6_1_1");
					put(grammarAccess.getRulSSH_commandsAccess().getRemoteCommandAssignment_1(), "rule__RulSSH_commands__RemoteCommandAssignment_1");
					put(grammarAccess.getRulSSH_commandsAccess().getScriptparamsAssignment_2_1(), "rule__RulSSH_commands__ScriptparamsAssignment_2_1");
					put(grammarAccess.getRuleHTTPAccess().getRemoteMachineAssignment_5(), "rule__RuleHTTP__RemoteMachineAssignment_5");
					put(grammarAccess.getRuleHTTPAccess().getHttpURLAssignment_9(), "rule__RuleHTTP__HttpURLAssignment_9");
					put(grammarAccess.getRuleHTTPAccess().getHMethodAssignment_13(), "rule__RuleHTTP__HMethodAssignment_13");
					put(grammarAccess.getRuleHTTPAccess().getAuthMethodAssignment_15_4(), "rule__RuleHTTP__AuthMethodAssignment_15_4");
					put(grammarAccess.getRuleHTTPAccess().getUsernameAssignment_15_8(), "rule__RuleHTTP__UsernameAssignment_15_8");
					put(grammarAccess.getRuleHTTPAccess().getPasswordAssignment_15_12(), "rule__RuleHTTP__PasswordAssignment_15_12");
					put(grammarAccess.getRuleHTTPAccess().getPostBodyAssignment_16_2(), "rule__RuleHTTP__PostBodyAssignment_16_2");
					put(grammarAccess.getRuleHTTP_URLAccess().getRemoteURLAssignment_1(), "rule__RuleHTTP_URL__RemoteURLAssignment_1");
					put(grammarAccess.getRuleHTTP_URLAccess().getScriptparamsAssignment_2_1(), "rule__RuleHTTP_URL__ScriptparamsAssignment_2_1");
					put(grammarAccess.getRuleXMLRPCAccess().getRemoteMachineAssignment_5(), "rule__RuleXMLRPC__RemoteMachineAssignment_5");
					put(grammarAccess.getRuleXMLRPCAccess().getUsernameAssignment_7_4(), "rule__RuleXMLRPC__UsernameAssignment_7_4");
					put(grammarAccess.getRuleXMLRPCAccess().getPasswordAssignment_7_8(), "rule__RuleXMLRPC__PasswordAssignment_7_8");
					put(grammarAccess.getRuleXMLRPCAccess().getRPCMethodAssignment_10(), "rule__RuleXMLRPC__RPCMethodAssignment_10");
					put(grammarAccess.getRuleXMLRPCAccess().getURLparamsAssignment_12_2(), "rule__RuleXMLRPC__URLparamsAssignment_12_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			gr.upatras.ece.wcl.radl2.ui.contentassist.antlr.internal.InternalRadlParser typedParser = (gr.upatras.ece.wcl.radl2.ui.contentassist.antlr.internal.InternalRadlParser) parser;
			typedParser.entryRuleRADL();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RadlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RadlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
